---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: blog/.vuepress/data/config.json
  label: Config
- type: directory
  path: blog/posts
  label: Categories
  create: all
  match: "**/*"
upload_dir: blog/.vuepress/public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
